name: Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install --no-audit --no-fund --no-optional

      - name: Run Tests
        id: run-tests
        run: npm test

      - name: Check coverage threshold
        if: steps.run-tests.outcome == 'success'
        run: npm run check-coverage

      - name: Login to Azure Registry
        uses: azure/docker-login@v1
        with:
          login-server: wwebe.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME_TEST }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD_TEST }}
      - name: Push to Azure Registry
        run: |
          docker build . -t wwebe.azurecr.io/wwebe:latest
          docker push wwebe.azurecr.io/wwebe:latest

  stop-on-failure:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.test.result != 'success' }}
    
    steps:
      - name: Stop Pipeline on Failure
        run: exit 1
